### ISSUE TITLE
Create a tag for tap-1.1

### ISSUE THREAD

**Issue by teddyking** [sample-accelerators/spring-sensors-rabbit#3]
Hi there,

Would it be possible to create a git tag `tap-1.1` in this repository? I'd like to refer to this app in the TAP documentation and would prefer to do that by tag rather than relying on the `main` branch.

Thanks!

**Comment by trisberg** [comment]
This app is no longer maintained and will be archived - please use https://github.com/tanzu-end-to-end/spring-sensors/tree/rabbit instead
